### ISSUE TITLE
Design run tracking system

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/neuron_morphology#157]
Flesh out this design a little more, including how data gets populated, how we address database maintenance tasks (backups, etc), how to query it.

**Comment by NileGraddis** [comment]
More detailed reqs from meeting:

entities
======
- specimen
- reconstruction
- run (date, pipeline, latest successful pipeline stage)
- pipeline version
- project

stories
=====

1. As a data manager, I would like to download 
- transformed swc
- raw swc
- marker file
for the most recent run of a given list of specimens, if that run was successful, so that I analyze these data with the neuron_morphology package.
- if the most recent run was a failure, it should be reported to the user of this query

2. As a data manager, I would like to generate a report of the status of an argued list of specimens, so that I can get a sense of the overall health of the pipeline.

3. As a data manager, I would like to obtain a mapping from specimen to most recent successful run over all specimens, in order to know which data to download.

4. As a data manager, I would like to obtain a list of specimens whose most recent run is a failure, in order to detect new bugs.

general criteria
============
- queries should support filtering by general fields, such as pipeline version, reconstruction, project, or run date
- queries should support filtering to latest run
- the interface needs to be straightforward for a technical user, but is otherwise unconstrained.

**Comment by NileGraddis** [comment]
See #171 for our plan
